name: Canary Release

on:
  push:
    branches:
      - main
      - docusaurus-v**
    paths:
      - packages/**

permissions:
  contents: read

jobs:
  publish-canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          fetch-depth: 0 # Needed to get the commit number with "git rev-list --count HEAD"
      - name: Set up Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3
        with:
          node-version: '16'
          cache: yarn
      - name: Prepare git
        run: |
          git config --global user.name "Docusaurus Canary"
          git config --global user.email "canary@docusaurus.io"
          git fetch
          git checkout main
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          cat .npmrc
          echo "npm whoami"
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Installation
        run: yarn
      - name: Publish Canary release
        run: |
          yarn canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
